global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    consul_sd_configs:
      - server: 'http://consul:8500'
        services: ['products-service', 'users-service', 'services-service', 'schedules-service', 'orders-service']
