spring:
  application:
    name: schedules-service
  datasource:
    url: jdbc:mysql://localhost:3306/RCF_SOLUCIONES_INFORMATICAS_SCHEDULES_SERVICE?useSSL=false&allowPublicKeyRetrieval=true&serverTimeZone=UTC&autoReconnect=true
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/realms/rfc-soluciones-informaticas
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha


server:
  port: 8087